### ISSUE TITLE
Google的开源规范

### ISSUE THREAD

**Issue by Ir1d** [ee0703/python-style-guide#1]
在README中提到目前没有一个比较完整的规范……

个人感觉Google的风格不错阿

FYI：http://google.github.io/styleguide/pyguide.html

**Comment by ee0703** [comment]
google的代码规范还是比较全的，整理的时候也参考了一些google的style，但是google这个好像没有单元测试规范

**Comment by Ir1d** [comment]
:+1: Thanks!
